### ISSUE TITLE
support: missing ) after argument list

### ISSUE THREAD

**Issue by dima-po** [waldronmatt/html-validate-webpack-plugin#1]
# Support Question
After launching webpack I get an error
![image](https://user-images.githubusercontent.com/11406634/152116085-c1ebb14e-cd7d-46bf-b1c5-1f9e4e096046.png)

installed according to the instructions

**Comment by waldronmatt** [comment]
It's recommended to install `html-validate` globally: `npm i -g html-validate` vs. locally.  The newest release of this plugin removes local scope and enables global scope by default for more consistent behavior across environments and operating systems. https://github.com/waldronmatt/html-validate-webpack-plugin/releases/tag/v1.2.1
